name: App
version: 0.3.1
entry: start.chapter1
author: bakakasin@gmail.com
debug: false
mode: all #once #Динамически подгружает assets
keywords: 
   - vnjson
   - simple example
   - Vnjson Script
   - text quest
